version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: unisanayi_db
    environment:
      POSTGRES_DB: unisanayi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: